#!/usr/bin/env bash
#SBATCH -A NAISS2025-22-855 -p alvis       # project
#SBATCH -N 1 --gpus-per-node=A100:4        # 1 Node, 4 GPUs per node
#SBATCH -t 0-02:00:00                      # runtime max limit (2 hours)
#SBATCH -J deepseekocr-job                 # job name
#SBATCH -o deepseekocr_%j.out              # output file
#SBATCH -e deepseekocr_%j.err              # error file

echo "Job started: $(date)"
echo "Running on nodes:"
scontrol show hostnames $SLURM_NODELIST

# load modules (needed for Alvis / squeue)
module load Python/3.11.3-GCCcore-12.3.0 virtualenv/20.23.1-GCCcore-12.3.0 JupyterLab/4.0.5-GCCcore-12.3.0

# activate venv
source ocr_env/bin/activate

# run script
python deepseekocr.py

echo "Job finished: $(date)"
