#!/usr/bin/env bash
#SBATCH -A NAISS2025-22-855 -p alvis       # Your project/account
#SBATCH -N 1 --gpus-per-node=A40:4        # 1 Node, 4 GPUs per node
#SBATCH -t 0-02:00:00                      # Runtime limit (2 hour)
#SBATCH -J deepseekocr-job                 # Job name
#SBATCH -o deepseekocr-a40_%j.out              # Output file
#SBATCH -e deepseekocr-a40_%j.err              # Error file

echo "Job started on $(date)"
echo "Running on nodes:"
scontrol show hostnames $SLURM_NODELIST

# load needed modules
module load Python/3.11.3-GCCcore-12.3.0 virtualenv/20.23.1-GCCcore-12.3.0 JupyterLab/4.0.5-GCCcore-12.3.0

# activate venv
source ocr_env/bin/activate

# run script
python deepseekocrA40.py

echo "Job finished on $(date)"
